### ISSUE TITLE
Typo on image (sha236 instead of sha256)

### ISSUE THREAD

**Issue by bordalix** [bitcoin-dev-project/bitcoin-dev-project#121]
This image has a typo, twice (sha236 instead of sha256)

https://bitcoindevs.xyz/bitcoin-topics/static/images/topics/taproot/tag.svg

**Comment by jrakibi** [comment]
fixed here https://github.com/bitcoin-dev-project/decoding-bitcoin/pull/22/files
thanks @bordalix for your contribution

**Comment by jrakibi** [comment]
fixed here https://github.com/bitcoin-dev-project/decoding-bitcoin/pull/22/files
thanks @bordalix for your contribution
