### ISSUE TITLE
Integrate Tailwind/Next.js Starter Template into BDP Website

### ISSUE THREAD

**Issue by jrakibi** [bitcoin-dev-project/bitcoin-dev-project#59]
We are integrating a Tailwind/Next.js Starter Template into the BDP website to create the glossary. 

This [template](https://github.com/timlrx/tailwind-nextjs-starter-blog) provides a basic structure, easy configuration, and customizable solution to help us kickstart building the glossary. 
It uses Contentlayer, which automates the conversion of Markdown files into type-safe, structured data for easier and more efficient content management.

Tasks:
- [x]  Integrate Contentlayer for managing content logic
- [x]  Use MDX and display embedded React components within the content
- [x]  Show each author/volunteer page
- [ ]  Display posts of each author
- [x]  Add tags for topics
- [ ]  Display topics by tags (each unique tag will be its own page)
- [ ]  Add SEO metadata, sitemaps, ..
- [x] Display the content of the markdown
- [x] List all topics + Pagination
- [x]  Sync the glossary files from the remote [repo](https://github.com/bitcoin-dev-project/glossary/) source to our local BDP website
- [ ]  Add support for analytic tools like Umami

Optional? :
- [ ] Add comment system to let users leave comments on topics
- [ ] Newsletter API and component with support for Mailchimp,

**Comment by adamjonas** [comment]
Can we close this @jrakibi ?

**Comment by jrakibi** [comment]
> Can we close this @jrakibi ?

yes. closed
