### ISSUE TITLE
Responsiveness Fixes

### ISSUE THREAD

**Issue by jrakibi** [bitcoin-dev-project/bitcoin-dev-project#84]
These are the changes we need to fix:

- [x] When refreshing the page, the icon for dark/light mode disappears for a few milliseconds and then reappears
- [x] Remove the small gray background color showing on the pagination for "good-first-issues"
- [x] Center the screenshot for ChatBTC
- [x] The section containing screenshots for "good-first-issues" and "Topics" should be responsive on mobile
- [x] Clicking on "Subscribe" should subscribe to the TLDR newsletter
- [x]  Dark mode for the search icon, hover text, selected filter text, lightning icon might need some improvement as some are not quite legible 
![image](https://github.com/bitcoin-dev-project/bitcoin-dev-project/assets/19940301/bdfad41b-fdbd-4117-bbcd-e0a6f66389c7)

- [x]  On scrolling on the good first issues page the navbar is no longer static which creates the disparity in the screen shot
![image](https://github.com/bitcoin-dev-project/bitcoin-dev-project/assets/19940301/13e29c05-a8d0-48ad-9023-7eb7dc3e8303)

- [x] Bug: on open and close of mobile nav redirects user to home page. This happens when you're on another page that is not the home page and don't navigate to any specific page or route but click on the nav menu icon to close it modal. 
- [x] Center contribute section in landing page on ipad screen

**Comment by IgboPharaoh** [comment]
I think you can you can close this now as all issues has been added to.
